[package]
name = "gabby"
version = "0.1.0"
authors = ["Antwan van Houdt <a.vanhoudt@wearetriple.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
